package com.mycompany.priorityhealth;
// Generated 6/09/2015 06:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Autorizaciones generated by hbm2java
 */
@Entity
@Table(name="Autorizaciones"
    ,catalog="cosw2"
)
public class Autorizaciones  implements java.io.Serializable {


     private int numero;
     private Epsafilidas epsafilidas;
     private Date fechaExpedicion;
     private Date fechaVencimiento;
     private Set medicamentoses = new HashSet(0);

    public Autorizaciones() {
    }

	
    public Autorizaciones(int numero, Epsafilidas epsafilidas) {
        this.numero = numero;
        this.epsafilidas = epsafilidas;
    }
    public Autorizaciones(int numero, Epsafilidas epsafilidas, Date fechaExpedicion, Date fechaVencimiento, Set medicamentoses) {
       this.numero = numero;
       this.epsafilidas = epsafilidas;
       this.fechaExpedicion = fechaExpedicion;
       this.fechaVencimiento = fechaVencimiento;
       this.medicamentoses = medicamentoses;
    }
   
     @Id 

    
    @Column(name="numero", unique=true, nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EPSAfilidas_idEPS", nullable=false)
    public Epsafilidas getEpsafilidas() {
        return this.epsafilidas;
    }
    
    public void setEpsafilidas(Epsafilidas epsafilidas) {
        this.epsafilidas = epsafilidas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaExpedicion", length=10)
    public Date getFechaExpedicion() {
        return this.fechaExpedicion;
    }
    
    public void setFechaExpedicion(Date fechaExpedicion) {
        this.fechaExpedicion = fechaExpedicion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaVencimiento", length=10)
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="autorizaciones")
    public Set getMedicamentoses() {
        return this.medicamentoses;
    }
    
    public void setMedicamentoses(Set medicamentoses) {
        this.medicamentoses = medicamentoses;
    }




}


