package com.mycompany.priorityhealth;
// Generated 6/09/2015 06:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContratosId generated by hbm2java
 */
@Embeddable
public class ContratoId  implements java.io.Serializable {


     private int idContrato;
     private int epsafilidasIdEps;

    public ContratoId() {
    }

    public ContratoId(int idContrato, int epsafilidasIdEps) {
       this.idContrato = idContrato;
       this.epsafilidasIdEps = epsafilidasIdEps;
    }
   


    @Column(name="idContratos", nullable=false)
    public int getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }


    @Column(name="EPSAfilidas_idEPS", nullable=false)
    public int getEpsafilidasIdEps() {
        return this.epsafilidasIdEps;
    }
    
    public void setEpsafilidasIdEps(int epsafilidasIdEps) {
        this.epsafilidasIdEps = epsafilidasIdEps;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContratoId) ) return false;
		 ContratoId castOther = ( ContratoId ) other; 
         
		 return (this.getIdContrato()==castOther.getIdContrato())
 && (this.getEpsafilidasIdEps()==castOther.getEpsafilidasIdEps());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdContrato();
         result = 37 * result + this.getEpsafilidasIdEps();
         return result;
   }   


}


