package com.mycompany.priorityhealth;
// Generated 6/09/2015 06:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contratos generated by hbm2java
 */
@Entity
@Table(name="Contratos"
    ,catalog="cosw2"
)
public class Contrato  implements java.io.Serializable {


     private ContratoId id;
     private Epsafilida epsafilida;
     private String descripcion;
     private String numeroAfiliados;
     private String precioPorAfiliado;

    public Contrato() {
    }

	
    public Contrato(ContratoId id, Epsafilida epsafilida) {
        this.id = id;
        this.epsafilida = epsafilida;
    }
    public Contrato(ContratoId id, Epsafilida epsafilida, String descripcion, String numeroAfiliados, String precioPorAfiliado) {
       this.id = id;
       this.epsafilida = epsafilida;
       this.descripcion = descripcion;
       this.numeroAfiliados = numeroAfiliados;
       this.precioPorAfiliado = precioPorAfiliado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idContratos", column=@Column(name="idContratos", nullable=false) ), 
        @AttributeOverride(name="epsafilidasIdEps", column=@Column(name="EPSAfilidas_idEPS", nullable=false) ) } )
    public ContratoId getId() {
        return this.id;
    }
    
    public void setId(ContratoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EPSAfilidas_idEPS", nullable=false, insertable=false, updatable=false)
    public Epsafilida getEpsafilida() {
        return this.epsafilida;
    }
    
    public void setEpsafilida(Epsafilida epsafilida) {
        this.epsafilida = epsafilida;
    }

    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="NumeroAfiliados", length=45)
    public String getNumeroAfiliados() {
        return this.numeroAfiliados;
    }
    
    public void setNumeroAfiliados(String numeroAfiliados) {
        this.numeroAfiliados = numeroAfiliados;
    }

    
    @Column(name="precioPorAfiliado", length=45)
    public String getPrecioPorAfiliado() {
        return this.precioPorAfiliado;
    }
    
    public void setPrecioPorAfiliado(String precioPorAfiliado) {
        this.precioPorAfiliado = precioPorAfiliado;
    }




}


