package com.mycompany.priorityhealth;
// Generated Sep 4, 2015 12:17:33 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallesPedido generated by hbm2java
 */
@Entity
@Table(name="DetallesPedido"
    ,catalog="cosw2"
)
public class DetallesPedido  implements java.io.Serializable {


     private DetallesPedidoId id;
     private MedicamentosPorProveedor medicamentosPorProveedor;
     private Pedidos pedidos;
     private String cantidad;

    public DetallesPedido() {
    }

	
    public DetallesPedido(DetallesPedidoId id, MedicamentosPorProveedor medicamentosPorProveedor, Pedidos pedidos) {
        this.id = id;
        this.medicamentosPorProveedor = medicamentosPorProveedor;
        this.pedidos = pedidos;
    }
    public DetallesPedido(DetallesPedidoId id, MedicamentosPorProveedor medicamentosPorProveedor, Pedidos pedidos, String cantidad) {
       this.id = id;
       this.medicamentosPorProveedor = medicamentosPorProveedor;
       this.pedidos = pedidos;
       this.cantidad = cantidad;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idMedicamentos", column=@Column(name="idMedicamentos", nullable=false) ), 
        @AttributeOverride(name="idPedidos", column=@Column(name="idPedidos", nullable=false, length=45) ) } )
    public DetallesPedidoId getId() {
        return this.id;
    }
    
    public void setId(DetallesPedidoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MedicamentosPorProveedor_idDetalleCompra", nullable=false)
    public MedicamentosPorProveedor getMedicamentosPorProveedor() {
        return this.medicamentosPorProveedor;
    }
    
    public void setMedicamentosPorProveedor(MedicamentosPorProveedor medicamentosPorProveedor) {
        this.medicamentosPorProveedor = medicamentosPorProveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Pedidos_idPedidos", nullable=false)
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }

    
    @Column(name="cantidad", length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }




}


