package com.mycompany.priorityhealth;
// Generated Sep 4, 2015 12:17:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetallesPedidoId generated by hbm2java
 */
@Embeddable
public class DetallesPedidoId  implements java.io.Serializable {


     private int idMedicamentos;
     private String idPedidos;

    public DetallesPedidoId() {
    }

    public DetallesPedidoId(int idMedicamentos, String idPedidos) {
       this.idMedicamentos = idMedicamentos;
       this.idPedidos = idPedidos;
    }
   


    @Column(name="idMedicamentos", nullable=false)
    public int getIdMedicamentos() {
        return this.idMedicamentos;
    }
    
    public void setIdMedicamentos(int idMedicamentos) {
        this.idMedicamentos = idMedicamentos;
    }


    @Column(name="idPedidos", nullable=false, length=45)
    public String getIdPedidos() {
        return this.idPedidos;
    }
    
    public void setIdPedidos(String idPedidos) {
        this.idPedidos = idPedidos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallesPedidoId) ) return false;
		 DetallesPedidoId castOther = ( DetallesPedidoId ) other; 
         
		 return (this.getIdMedicamentos()==castOther.getIdMedicamentos())
 && ( (this.getIdPedidos()==castOther.getIdPedidos()) || ( this.getIdPedidos()!=null && castOther.getIdPedidos()!=null && this.getIdPedidos().equals(castOther.getIdPedidos()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMedicamentos();
         result = 37 * result + ( getIdPedidos() == null ? 0 : this.getIdPedidos().hashCode() );
         return result;
   }   


}


