package com.mycompany.priorityhealth;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetallesOrdenComptaId generated by hbm2java
 */
@Entity
@Table(name="DetallesOrdenComptaId"
    ,catalog="cosw2"
)
public class DetallesOrdenComptaId  implements java.io.Serializable {


     private int idDetallesOrdenComptaId;
     private Integer idMedicamento;
     private Integer idOrdenCompra;

    public DetallesOrdenComptaId() {
    }

	
    public DetallesOrdenComptaId(int idDetallesOrdenComptaId) {
        this.idDetallesOrdenComptaId = idDetallesOrdenComptaId;
    }
    public DetallesOrdenComptaId(int idDetallesOrdenComptaId, Integer idMedicamento, Integer idOrdenCompra) {
       this.idDetallesOrdenComptaId = idDetallesOrdenComptaId;
       this.idMedicamento = idMedicamento;
       this.idOrdenCompra = idOrdenCompra;
    }
   
    @Id 
    @Column(name="idDetallesOrdenComptaId", unique=true, nullable=false)
    public int getIdDetallesOrdenComptaId() {
        return this.idDetallesOrdenComptaId;
    }
    
    public void setIdDetallesOrdenComptaId(int idDetallesOrdenComptaId) {
        this.idDetallesOrdenComptaId = idDetallesOrdenComptaId;
    }

    
    @Column(name="idMedicamento")
    public Integer getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(Integer idMedicamento) {
        this.idMedicamento = idMedicamento;
    }

    
    @Column(name="idOrdenCompra")
    public Integer getIdOrdenCompra() {
        return this.idOrdenCompra;
    }
    
    public void setIdOrdenCompra(Integer idOrdenCompra) {
        this.idOrdenCompra = idOrdenCompra;
    }




}