package com.mycompany.priorityhealth;
// Generated 6/09/2015 06:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallesPedido generated by hbm2java
 */
@Entity
@Table(name="DetallesPedido"
    ,catalog="cosw2"
)
public class DetallesPedido  implements java.io.Serializable {


     private int idDetalle;
     private MedicamentosPorProveedor medicamentosPorProveedor;
     private Pedido pedido;
     private String cantidad;

    public DetallesPedido() {
    }

	
    public DetallesPedido(int idDetalle, MedicamentosPorProveedor medicamentosPorProveedor, Pedido pedido) {
        this.idDetalle = idDetalle;
        this.medicamentosPorProveedor = medicamentosPorProveedor;
        this.pedido = pedido;
    }
    public DetallesPedido(int idDetalle, MedicamentosPorProveedor medicamentosPorProveedor, Pedido pedido, String cantidad) {
       this.idDetalle = idDetalle;
       this.medicamentosPorProveedor = medicamentosPorProveedor;
       this.pedido = pedido;
       this.cantidad = cantidad;
    }
   
     @Id 

    
    @Column(name="idDetalle", unique=true, nullable=false)
    public int getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(int idDetalle) {
        this.idDetalle = idDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MedicamentosPorProveedor_idDetalleCompra", nullable=false)
    public MedicamentosPorProveedor getMedicamentosPorProveedor() {
        return this.medicamentosPorProveedor;
    }
    
    public void setMedicamentosPorProveedor(MedicamentosPorProveedor medicamentosPorProveedor) {
        this.medicamentosPorProveedor = medicamentosPorProveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Pedidos_idPedidos", nullable=false)
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    
    @Column(name="cantidad", length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }




}


