/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.priorityhealth;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetallesOrdenesCompra generated by hbm2java
 */
@Entity
@Table(name="DetallesOrdenesCompra"
    ,catalog="cosw2"
)
public class DetallesOrdenesCompra  implements java.io.Serializable {


     private int idDetalleOrdenesCompra;
     private int medicamentosIdMedicamentos;
     private int ordenesCompraIdOrdenesCompra;
     private Integer cantidad;

    public DetallesOrdenesCompra() {
    }

	
    public DetallesOrdenesCompra(int idDetalleOrdenesCompra, int medicamentosIdMedicamentos, int ordenesCompraIdOrdenesCompra) {
        this.idDetalleOrdenesCompra = idDetalleOrdenesCompra;
        this.medicamentosIdMedicamentos = medicamentosIdMedicamentos;
        this.ordenesCompraIdOrdenesCompra = ordenesCompraIdOrdenesCompra;
    }
    public DetallesOrdenesCompra(int idDetalleOrdenesCompra, int medicamentosIdMedicamentos, int ordenesCompraIdOrdenesCompra, Integer cantidad) {
       this.idDetalleOrdenesCompra = idDetalleOrdenesCompra;
       this.medicamentosIdMedicamentos = medicamentosIdMedicamentos;
       this.ordenesCompraIdOrdenesCompra = ordenesCompraIdOrdenesCompra;
       this.cantidad = cantidad;
    }
   
     @Id 

    
    @Column(name="idDetalleOrdenesCompra", unique=true, nullable=false)
    public int getIdDetalleOrdenesCompra() {
        return this.idDetalleOrdenesCompra;
    }
    
    public void setIdDetalleOrdenesCompra(int idDetalleOrdenesCompra) {
        this.idDetalleOrdenesCompra = idDetalleOrdenesCompra;
    }

    
    @Column(name="Medicamentos_idMedicamentos", nullable=false)
    public int getMedicamentosIdMedicamentos() {
        return this.medicamentosIdMedicamentos;
    }
    
    public void setMedicamentosIdMedicamentos(int medicamentosIdMedicamentos) {
        this.medicamentosIdMedicamentos = medicamentosIdMedicamentos;
    }

    
    @Column(name="OrdenesCompra_idOrdenesCompra", nullable=false)
    public int getOrdenesCompraIdOrdenesCompra() {
        return this.ordenesCompraIdOrdenesCompra;
    }
    
    public void setOrdenesCompraIdOrdenesCompra(int ordenesCompraIdOrdenesCompra) {
        this.ordenesCompraIdOrdenesCompra = ordenesCompraIdOrdenesCompra;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


