package com.mycompany.priorityhealth;
// Generated 6/09/2015 06:30:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Epsafilidas generated by hbm2java
 */
@Entity
@Table(name="EPSAfilidas"
    ,catalog="cosw2"
)
public class Epsafilida  implements java.io.Serializable {


     private int idEps;
     private String nombre;
     private String regimen;
     private String correo;
     private Set<Contrato> contratos = new HashSet(0);
     private Set<Autorizacion> autorizaciones = new HashSet(0);
     private Set<Paciente> pacientes = new HashSet(0);

    public Epsafilida() {
    }

	
    public Epsafilida(int idEps, String nombre, String regimen) {
        this.idEps = idEps;
        this.nombre = nombre;
        this.regimen = regimen;
    }
    public Epsafilida(int idEps, String nombre, String regimen, String correo, Set<Contrato> contratos, Set<Autorizacion> autorizaciones, Set<Paciente> pacientes) {
       this.idEps = idEps;
       this.nombre = nombre;
       this.regimen = regimen;
       this.correo = correo;
       this.contratos = contratos;
       this.autorizaciones = autorizaciones;
       this.pacientes = pacientes;
    }
   
     @Id 

    
    @Column(name="idEPS", unique=true, nullable=false)
    public int getIdEps() {
        return this.idEps;
    }
    
    public void setIdEps(int idEps) {
        this.idEps = idEps;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="regimen", nullable=false, length=45)
    public String getRegimen() {
        return this.regimen;
    }
    
    public void setRegimen(String regimen) {
        this.regimen = regimen;
    }

    
    @Column(name="correo", length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epsafilidas")
    public Set<Contrato> getContratos() {
        return this.contratos;
    }
    
    public void setContratoses(Set<Contrato> contratos) {
        this.contratos = contratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epsafilidas")
    public Set<Autorizacion> getAutorizaciones() {
        return this.autorizaciones;
    }
    
    public void setAutorizaciones(Set<Autorizacion> autorizaciones) {
        this.autorizaciones = autorizaciones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epsafilidas")
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }




}


