package com.mycompany.priorityhealth;
// Generated Sep 4, 2015 12:17:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name="Inventario"
    ,catalog="cosw2"
)
public class Inventario  implements java.io.Serializable {


     private int idInventario;
     private MedicamentosPorProveedor medicamentosPorProveedor;
     private String cantidad;
     private String inventariocol;

    public Inventario() {
    }

	
    public Inventario(int idInventario, MedicamentosPorProveedor medicamentosPorProveedor) {
        this.idInventario = idInventario;
        this.medicamentosPorProveedor = medicamentosPorProveedor;
    }
    public Inventario(int idInventario, MedicamentosPorProveedor medicamentosPorProveedor, String cantidad, String inventariocol) {
       this.idInventario = idInventario;
       this.medicamentosPorProveedor = medicamentosPorProveedor;
       this.cantidad = cantidad;
       this.inventariocol = inventariocol;
    }
   
     @Id 

    
    @Column(name="idInventario", unique=true, nullable=false)
    public int getIdInventario() {
        return this.idInventario;
    }
    
    public void setIdInventario(int idInventario) {
        this.idInventario = idInventario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MedicamentosPorProveedor_idDetalleCompra", nullable=false)
    public MedicamentosPorProveedor getMedicamentosPorProveedor() {
        return this.medicamentosPorProveedor;
    }
    
    public void setMedicamentosPorProveedor(MedicamentosPorProveedor medicamentosPorProveedor) {
        this.medicamentosPorProveedor = medicamentosPorProveedor;
    }

    
    @Column(name="cantidad", length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="Inventariocol", length=45)
    public String getInventariocol() {
        return this.inventariocol;
    }
    
    public void setInventariocol(String inventariocol) {
        this.inventariocol = inventariocol;
    }




}


