package com.mycompany.priorityhealth;
// Generated 6/09/2015 06:30:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name="Inventario"
    ,catalog="cosw2"
)
public class Inventario  implements java.io.Serializable {


     private int idInventario;
     private MedicamentosPorProveedor medicamentosPorProveedor;
     private String cantidad;

    public Inventario() {
    }

	
    public Inventario(int idInventario, MedicamentosPorProveedor medicamentosPorProveedor) {
        this.idInventario = idInventario;
        this.medicamentosPorProveedor = medicamentosPorProveedor;
    }
    public Inventario(int idInventario, MedicamentosPorProveedor medicamentosPorProveedor, String cantidad) {
       this.idInventario = idInventario;
       this.medicamentosPorProveedor = medicamentosPorProveedor;
       this.cantidad = cantidad;
    }
   
     @Id 

    
    @Column(name="idInventario", unique=true, nullable=false)
    public int getIdInventario() {
        return this.idInventario;
    }
    
    public void setIdInventario(int idInventario) {
        this.idInventario = idInventario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MedicamentosPorProveedor_idDetalleCompra", nullable=false)
    public MedicamentosPorProveedor getMedicamentosPorProveedor() {
        return this.medicamentosPorProveedor;
    }
    
    public void setMedicamentosPorProveedor(MedicamentosPorProveedor medicamentosPorProveedor) {
        this.medicamentosPorProveedor = medicamentosPorProveedor;
    }

    
    @Column(name="cantidad", length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }




}


