package com.mycompany.priorityhealth;
// Generated 6/09/2015 06:30:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedicamentosPorProveedor generated by hbm2java
 */
@Entity
@Table(name="MedicamentosPorProveedor"
    ,catalog="cosw2"
)
public class MedicamentosPorProveedor  implements java.io.Serializable {


     private int idDetalleCompra;
     private Medicamento medicamento;
     private Proveedor proveedor;
     private Integer idProveedor;
     private Integer idMedicamento;
     private String precio;
     private Set<DetallesPedido> detallesPedidos = new HashSet(0);
     private Set<Inventario> inventarios = new HashSet(0);

    public MedicamentosPorProveedor() {
    }

	
    public MedicamentosPorProveedor(int idDetalleCompra, Medicamento medicamento, Proveedor proveedor) {
        this.idDetalleCompra = idDetalleCompra;
        this.medicamento = medicamento;
        this.proveedor = proveedor;
    }
    public MedicamentosPorProveedor(int idDetalleCompra, Medicamento medicamento, Proveedor proveedor, Integer idProveedor, Integer idMedicamento, String precio, Set<DetallesPedido> detallesPedidos, Set<Inventario> inventarios) {
       this.idDetalleCompra = idDetalleCompra;
       this.medicamento = medicamento;
       this.proveedor = proveedor;
       this.idProveedor = idProveedor;
       this.idMedicamento = idMedicamento;
       this.precio = precio;
       this.detallesPedidos = detallesPedidos;
       this.inventarios = inventarios;
    }
   
     @Id 

    
    @Column(name="idDetalleCompra", unique=true, nullable=false)
    public int getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(int idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Medicamentos_idMedicamentos", nullable=false)
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Proveedores_idProveedores", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    
    @Column(name="idProveedores")
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="idMedicamentos")
    public Integer getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(Integer idMedicamento) {
        this.idMedicamento = idMedicamento;
    }

    
    @Column(name="Precio", length=45)
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set<DetallesPedido> getDetallesPedidos() {
        return this.detallesPedidos;
    }
    
    public void setDetallesPedidos(Set<DetallesPedido> detallesPedidos) {
        this.detallesPedidos = detallesPedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicamentosPorProveedor")
    public Set<Inventario> getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set<Inventario>  inventarios) {
        this.inventarios = inventarios;
    }




}


