package com.mycompany.priorityhealth;
// Generated 6/09/2015 06:30:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mensajeros generated by hbm2java
 */
@Entity
@Table(name="Mensajeros"
    ,catalog="cosw2"
)
public class Mensajero  implements java.io.Serializable {


     private int idEmpleado;
     private String nombre;
     private String cargo;
     private String salario;
     private Integer telefono;
     private String direccion;
     private String correo;
     private Set<Despacho> despachos = new HashSet(0);

    public Mensajero() {
    }

	
    public Mensajero(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Mensajero(int idEmpleado, String nombre, String cargo, String salario, Integer telefono, String direccion, String correo, Set<Despacho> despachos) {
       this.idEmpleado = idEmpleado;
       this.nombre = nombre;
       this.cargo = cargo;
       this.salario = salario;
       this.telefono = telefono;
       this.direccion = direccion;
       this.correo = correo;
       this.despachos = despachos;
    }
   
     @Id 

    
    @Column(name="idEmpleados", unique=true, nullable=false)
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="cargo", length=45)
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    
    @Column(name="salario", length=45)
    public String getSalario() {
        return this.salario;
    }
    
    public void setSalario(String salario) {
        this.salario = salario;
    }

    
    @Column(name="telefono")
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="correo", length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mensajeros")
    public Set<Despacho> getDespachos() {
        return this.despachos;
    }
    
    public void setDespachos(Set<Despacho> despachos) {
        this.despachos = despachos;
    }




}


