package com.mycompany.priorityhealth;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdenesCompra generated by hbm2java
 */

@Entity
@Table(name="OrdenesCompra"
    ,catalog="cosw2"
)
public class OrdenesCompra  implements java.io.Serializable {


     private int idOrdenesCompra;
     private Integer cantidad;
     private Date fecha;
     private Set<DetallesOrdenComptaId> almDetallesCompra = new HashSet<DetallesOrdenComptaId>(0);

    public OrdenesCompra(Date fecha) {
        this.fecha=fecha;
    }

	
    public OrdenesCompra(int idOrdenesCompra) {
        this.idOrdenesCompra = idOrdenesCompra;
    }
    public OrdenesCompra(int idOrdenesCompra, Integer cantidad, Date fecha,  Set<DetallesOrdenComptaId> almDetallesCompra) {
       this.idOrdenesCompra = idOrdenesCompra;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.almDetallesCompra = almDetallesCompra;
    }
   
    @Id 
    @GeneratedValue
    @Column(name="idOrdenesCompra", unique=true, nullable=false)
    public int getIdOrdenesCompra() {
        return this.idOrdenesCompra;
    }
    
    public void setIdOrdenesCompra(int idOrdenesCompra) {
        this.idOrdenesCompra = idOrdenesCompra;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ordenesCompra")
    public Set<DetallesOrdenComptaId> getDetallesOrdenComtaId() {
        return this.almDetallesCompra;
    }
    
    public void setDetallesOrdenComtaId(Set<DetallesOrdenComptaId> almDetallesCompra) {
        this.almDetallesCompra = almDetallesCompra;
    }




}





