package com.mycompany.priorityhealth;
// Generated 6/09/2015 06:30:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="Pedidos"
    ,catalog="cosw2"
)
public class Pedido  implements java.io.Serializable {


     private int idPedido;
     private Paciente paciente;
     private Date fechaLlegada;
     private String direccion;
     private Set<Despacho> despachos = new HashSet(0);
     private Set<DetallesPedido> detallesPedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(int idPedido, Paciente paciente) {
        this.idPedido = idPedido;
        this.paciente = paciente;
    }
    public Pedido(int idPedido, Paciente paciente, Date fechaLlegada, String direccion, Set<Despacho> despachos, Set<DetallesPedido> detallesPedidos) {
       this.idPedido = idPedido;
       this.paciente = paciente;
       this.fechaLlegada = fechaLlegada;
       this.direccion = direccion;
       this.despachos = despachos;
       this.detallesPedidos = detallesPedidos;
    }
   
     @Id 

    
    @Column(name="idPedidos", unique=true, nullable=false)
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Pacientes_idPacientes", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaLlegada", length=10)
    public Date getFechaLlegada() {
        return this.fechaLlegada;
    }
    
    public void setFechaLlegada(Date fechaLlegada) {
        this.fechaLlegada = fechaLlegada;
    }

    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedidos")
    public Set<Despacho> getDespachos() {
        return this.despachos;
    }
    
    public void setDespachos(Set<Despacho> despachos) {
        this.despachos = despachos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedido")
    public Set<DetallesPedido> getDetallesPedidos() {
        return this.detallesPedidos;
    }
    
    public void setDetallesPedidos(Set<DetallesPedido> detallesPedidos) {
        this.detallesPedidos = detallesPedidos;
    }




}


