package com.mycompany.priorityhealth;
// Generated 6/09/2015 06:30:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedores generated by hbm2java
 */
@Entity
@Table(name="Proveedores"
    ,catalog="cosw2"
)
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private String nombre;
     private String telefono;
     private String direccion;
     private String pais;
     private Set<MedicamentosPorProveedor> medicamentosPorProveedores = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Proveedor(int idProveedor, String nombre, String telefono, String direccion, String pais, Set<MedicamentosPorProveedor> medicamentosPorProveedores) {
       this.idProveedor = idProveedor;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.pais = pais;
       this.medicamentosPorProveedores = medicamentosPorProveedores;
    }
   
     @Id 

    
    @Column(name="idProveedores", unique=true, nullable=false)
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="pais", length=45)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedores")
    public Set<MedicamentosPorProveedor> getMedicamentosPorProveedores() {
        return this.medicamentosPorProveedores;
    }
    
    public void setMedicamentosPorProveedores(Set<MedicamentosPorProveedor> medicamentosPorProveedor) {
        this.medicamentosPorProveedores = medicamentosPorProveedor;
    }




}


